---
title: "Practica"
output: pdf_document
date: "2022-11-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Inicializacion

Cargo el pacquete rjson para luego carga los articulos
```{r instalar_rjson}
if (! require('rjson')){
  !install.packages('rjson');
}
library('rjson');
```

Cargo el json con los articulos (durante las pruebas el reducido)
```{r cargar_json}
f = fromJSON(file = 'reduced_article_list.json');
ids = unlist(lapply(f$articles, function (x) x$id ));
titulos = unlist(lapply(f$articles, function (x) x$title ));
ano = unlist(lapply(f$articles, function (x) x$year ));
texto = unlist(lapply(f$articles, function (x) x$abstractText ));
df = data.frame(ids,titulos,ano,texto);

```
Ahora lo que vamos a hacer es buscar los afijos que nos sirvan para clasificar.

```{r busqueda}
library(stringr)
dolores = str_extract_all(df$texto, "\\w*algia")
alteraciones = str_extract_all(df$texto, "hiper\\w* | hipo\\w*")
infecciones = str_extract_all(df$texto, "\\w*itis")
cancer = str_extract_all(df$texto, "\\w*oma")
```
